import { insertRow,selectRows,updateRows,SupabaseError } from "./supabase.ts"; import { logEvent } from "./logger.ts"; import type { ChannelName } from "./env.ts";
export const RATE_WINDOW_MINUTES=10,RATE_MAX_REPLIES=20,DAILY_MAX_REPLIES=100,LOOP_WINDOW_SECONDS=20,LOOP_MAX_INBOUND=20;
export interface Conversation{id:string;channel:string;external_user_id:string;external_thread_id:string;customer_name:string|null;status:string;last_message_at:string;metadata:Record<string,unknown>;}
export async function claimEvent(channel:string,eventId:string,payloadDigest?:string):Promise<boolean>{try{await insertRow("ai_webhook_events",{channel,event_id:eventId,payload_digest:payloadDigest??null,status:"processing"});return true;}catch(e){if(e instanceof SupabaseError&&e.status===409){await logEvent({kind:"webhook_duplicate",channel,detail:{eventId}});return false;}throw e;}}
export async function finishEvent(channel:string,eventId:string,status:"done"|"failed",errorDetail?:string):Promise<void>{try{await updateRows("ai_webhook_events",`channel=eq.${encodeURIComponent(channel)}&event_id=eq.${encodeURIComponent(eventId)}`,{status,processed_at:new Date().toISOString(),error_detail:errorDetail?.slice(0,800)??null});}catch{}}
const OPTOUT=[/\bpar(e|ar) de (me )?(mandar|enviar)\b/i,/\bn[ãa]o quero (mais )?receber\b/i,/\bdescadastr/i,/\bsair da lista\b/i,/\bme remov/i,/\bcancelar? (o )?recebimento\b/i,/^\s*(sair|parar|stop)\s*$/i];
export function looksLikeOptOut(t:string):boolean{return OPTOUT.some(r=>r.test(String(t??"")));}
export async function isOptedOut(c:string,u:string):Promise<boolean>{return(await selectRows("ai_optouts",`select=id&channel=eq.${encodeURIComponent(c)}&external_user_id=eq.${encodeURIComponent(u)}&limit=1`)).length>0;}
export async function registerOptOut(c:string,u:string,reason:string):Promise<void>{try{await insertRow("ai_optouts",{channel:c,external_user_id:u,reason},{onConflict:"channel,external_user_id",ignoreDuplicates:true});}catch(e){if(!(e instanceof SupabaseError&&e.status===409))throw e;}await logEvent({kind:"optout",channel:c,detail:{reason}});}
export async function getOrCreateConversation(i:{channel:ChannelName|string;externalUserId:string;externalThreadId:string;customerName?:string|null;initialStatus?:"open"|"human";}):Promise<Conversation>{const f=`channel=eq.${encodeURIComponent(i.channel)}&external_user_id=eq.${encodeURIComponent(i.externalUserId)}&external_thread_id=eq.${encodeURIComponent(i.externalThreadId)}`;const x=await selectRows<Conversation>("ai_conversations",`select=*&${f}&limit=1`);if(x.length)return x[0];try{const c=await insertRow<Conversation>("ai_conversations",{channel:i.channel,external_user_id:i.externalUserId,external_thread_id:i.externalThreadId,customer_name:i.customerName??null,status:i.initialStatus??"open"});if(c)return c;}catch(e){if(!(e instanceof SupabaseError&&e.status===409))throw e;}const y=await selectRows<Conversation>("ai_conversations",`select=*&${f}&limit=1`);if(!y.length)throw new Error("não foi possível abrir a conversa");return y[0];}
export async function findConversation(c:string,u:string):Promise<Conversation|null>{const r=await selectRows<Conversation>("ai_conversations",`select=*&channel=eq.${encodeURIComponent(c)}&external_user_id=eq.${encodeURIComponent(u)}&order=last_message_at.desc&limit=1`);return r[0]??null;}
export async function messageExists(id:string):Promise<boolean>{return(await selectRows("ai_messages",`select=id&external_message_id=eq.${encodeURIComponent(id)}&limit=1`)).length>0;}
export async function touchConversation(id:string,patch:Record<string,unknown>={}):Promise<void>{await updateRows("ai_conversations",`id=eq.${id}`,{last_message_at:new Date().toISOString(),updated_at:new Date().toISOString(),...patch});}
export interface StoredMessage{id:string;direction:"inbound"|"outbound";message_type:string;text_content:string|null;image_analysis:Record<string,unknown>|null;created_at:string;raw_payload?:Record<string,any>;}
export async function recordMessage(i:{conversationId:string;direction:"inbound"|"outbound";messageType?:string;externalMessageId?:string|null;text?:string|null;mediaPath?:string|null;imageAnalysis?:Record<string,unknown>|null;rawPayload?:Record<string,unknown>|null;occurredAt?:string;}):Promise<StoredMessage|null>{try{return await insertRow<StoredMessage>("ai_messages",{conversation_id:i.conversationId,direction:i.direction,message_type:i.messageType??"text",external_message_id:i.externalMessageId??null,text_content:i.text??null,media_path:i.mediaPath??null,image_analysis:i.imageAnalysis??null,raw_payload:i.rawPayload??null,...(i.occurredAt?{created_at:i.occurredAt}:{})});}catch(e){if(e instanceof SupabaseError&&e.status===409)return null;throw e;}}
export async function getHistory(id:string,limit=12):Promise<StoredMessage[]>{return(await selectRows<StoredMessage>("ai_messages",`select=id,direction,message_type,text_content,image_analysis,created_at,raw_payload&conversation_id=eq.${id}&order=created_at.desc&limit=${limit}`)).reverse();}
async function count(id:string,d:"inbound"|"outbound",since:string):Promise<number>{const rows=await selectRows("ai_messages",`select=id,raw_payload&conversation_id=eq.${id}&direction=eq.${d}&created_at=gte.${encodeURIComponent(since)}&limit=1000`);const live=rows.filter(r=>r.raw_payload?.importedHistory!==true);return d==="inbound"?live.length:live.filter(r=>r.raw_payload?.enviado===true&&(r.raw_payload?.turn_complete===true||!r.raw_payload?.turnId)).length;}
export type GuardVerdict={allowed:true}|{allowed:false;reason:string;handoff:boolean};
export async function checkGuards(c:Conversation):Promise<GuardVerdict>{if(c.status==="human")return{allowed:false,reason:"conversa em atendimento humano",handoff:false};if(c.status==="closed")return{allowed:false,reason:"conversa encerrada",handoff:false};const n=Date.now();const[a,b,d]=await Promise.all([count(c.id,"outbound",new Date(n-RATE_WINDOW_MINUTES*60000).toISOString()),count(c.id,"outbound",new Date(n-24*3600000).toISOString()),count(c.id,"inbound",new Date(n-LOOP_WINDOW_SECONDS*1000).toISOString())]);if(d>=LOOP_MAX_INBOUND)return{allowed:false,reason:`${d} mensagens em ${LOOP_WINDOW_SECONDS}s — possível loop automático`,handoff:true};if(a>=RATE_MAX_REPLIES)return{allowed:false,reason:`limite de ${RATE_MAX_REPLIES} respostas em ${RATE_WINDOW_MINUTES} min atingido`,handoff:true};if(b>=DAILY_MAX_REPLIES)return{allowed:false,reason:`limite diário de ${DAILY_MAX_REPLIES} respostas atingido`,handoff:true};return{allowed:true};}
export async function openHandoff(c:Conversation,reason:string):Promise<void>{await touchConversation(c.id,{status:"human"});const o=await selectRows("ai_handoffs",`select=id&conversation_id=eq.${c.id}&status=eq.open&limit=1`);if(!o.length)await insertRow("ai_handoffs",{conversation_id:c.id,reason:reason.slice(0,500),status:"open"});await logEvent({kind:"handoff_opened",level:"warn",channel:c.channel,conversationId:c.id,detail:{reason}});}
const HANDOFF:Array<{re:RegExp;reason:string}>=[{re:/\b(atendente|humano|pessoa de verdade|falar com algu[ée]m|vendedora)\b/i,reason:"cliente pediu atendente"},{re:/\b(reclama[çc][ãa]o|p[ée]ssimo|horr[íi]vel|absurdo|inaceit[áa]vel|processo|procon)\b/i,reason:"reclamação"},{re:/\b(devolu[çc][ãa]o|trocar|troca|defeito|rasgad|estragad|veio errad)\b/i,reason:"troca ou devolução"},{re:/\b(desconto|abatimento|parcelar|negociar|cupom)\b/i,reason:"negociação comercial"},{re:/\b(estorno|reembolso|cobran[çc]a|n[ãa]o reconhe[çc]o|pix errado|paguei)\b/i,reason:"assunto financeiro"},{re:/\b(advogad|judicial|acionar)\b/i,reason:"assunto jurídico"}];
export function detectHandoffFromText(t:string):string|null{for(const{re,reason}of HANDOFF)if(re.test(String(t??"")))return reason;return null;}


